export const CITY_CREATE_REQUEST = 'CITY_CREATE_REQUEST'
export const CITY_CREATE_SUCCESS = 'CITY_CREATE_SUCCESS'
export const CITY_CREATE_FAIL = 'CITY_CREATE_FAIL'
export const CITY_CREATE_RESET = 'CITY_CREATE_RESET'