export const COUNTRY_CREATE_REQUEST = 'COUNTRY_CREATE_REQUEST'
export const COUNTRY_CREATE_SUCCESS = 'COUNTRY_CREATE_SUCCESS'
export const COUNTRY_CREATE_FAIL = 'COUNTRY_CREATE_FAIL'
export const COUNTRY_CREATE_RESET = 'COUNTRY_CREATE_RESET'