export const TOUR_LIST_REQUEST = 'TOUR_LIST_REQUEST'
export const TOUR_LIST_SUCCESS = 'TOUR_LIST_SUCCESS'
export const TOUR_LIST_FAIL = 'TOUR_LIST_FAIL'

export const TOUR_DETAILS_REQUEST = 'TOUR_DETAILS_REQUEST'
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS'
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL'

export const TOUR_CREATE_REQUEST = 'TOUR_CREATE_REQUEST'
export const TOUR_CREATE_SUCCESS = 'TOUR_CREATE_SUCCESS'
export const TOUR_CREATE_FAIL = 'TOUR_CREATE_FAIL'
export const TOUR_CREATE_RESET = 'TOUR_CREATE_RESET';

