export const TOUR_LIST_REQUEST = 'TOUR_LIST_REQUEST'
export const TOUR_LIST_SUCCESS = 'TOUR_LIST_SUCCESS'
export const TOUR_LIST_FAIL = 'TOUR_LIST_FAIL'

export const TOUR_LIST_BY_COUNTRY_REQUEST = 'TOUR_LIST_BY_COUNTRY_REQUEST'
export const TOUR_LIST_BY_COUNTRY_SUCCESS = 'TOUR_LIST_BY_COUNTRY_SUCCESS'
export const TOUR_LIST_BY_COUNTRY_FAIL = 'TOUR_LIST_BY_COUNTRY_FAIL'

export const TOUR_LIST_BY_CATEGORY_REQUEST = 'TOUR_LIST_BY_CATEGORY_REQUEST'
export const TOUR_LIST_BY_CATEGORY_SUCCESS = 'TOUR_LIST_BY_CATEGORY_SUCCESS'
export const TOUR_LIST_BY_CATEGORY_FAIL = 'TOUR_LIST_BY_CATEGORY_FAIL'
export const TOUR_LIST_BY_CATEGORY_RESET = 'TOUR_LIST_BY_CATEGORY_RESET'

export const TOUR_DETAILS_REQUEST = 'TOUR_DETAILS_REQUEST'
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS'
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL'
export const TOUR_DETAILS_RESET = 'TOUR_DETAILS_RESET'

export const TOUR_CREATE_REQUEST = 'TOUR_CREATE_REQUEST'
export const TOUR_CREATE_SUCCESS = 'TOUR_CREATE_SUCCESS'
export const TOUR_CREATE_FAIL = 'TOUR_CREATE_FAIL'
export const TOUR_CREATE_RESET = 'TOUR_CREATE_RESET'

export const TOUR_UPDATE_REQUEST = 'TOUR_UPDATE_REQUEST'
export const TOUR_UPDATE_SUCCESS = 'TOUR_UPDATE_SUCCESS'
export const TOUR_UPDATE_FAIL = 'TOUR_UPDATE_FAIL'
export const TOUR_UPDATE_RESET = 'TOUR_UPDATE_RESET'

export const TOUR_DELETE_REQUEST = 'TOUR_DELETE_REQUEST'
export const TOUR_DELETE_SUCCESS = 'TOUR_DELETE_SUCCESS'
export const TOUR_DELETE_FAIL = 'TOUR_DELETE_FAIL'
export const TOUR_DELETE_RESET = 'TOUR_DELETE_RESET'

export const TOUR_LIST_CATEGORY_REQUEST = 'TOUR_LIST_CATEGORY_REQUEST'
export const TOUR_LIST_CATEGORY_SUCCESS = 'TOUR_LIST_CATEGORY_SUCCESS'
export const TOUR_LIST_CATEGORY_FAIL = 'TOUR_LIST_CATEGORY_FAIL'
export const TOUR_LIST_CATEGORY_RESET = 'TOUR_LIST_CATEGORY_RESET'

export const TOUR_SEARCH_REQUEST = 'TOUR_SEARCH_REQUEST'
export const TOUR_SEARCH_SUCCESS = 'TOUR_SEARCH_SUCCESS'
export const TOUR_SEARCH_FAIL = 'TOUR_SEARCH_FAIL'
export const TOUR_SEARCH_RESET = 'TOUR_SEARCH_RESET'


export const TOUR_COMMENT_CREATE_REQUEST = 'TOUR_COMMENT_CREATE_REQUEST';
export const TOUR_COMMENT_CREATE_SUCCESS = 'TOUR_COMMENT_CREATE_SUCCESS';
export const TOUR_COMMENT_CREATE_FAIL = 'TOUR_COMMENT_CREATE_FAIL';
export const TOUR_COMMENT_CREATE_RESET = 'TOUR_COMMENT_CREATE_RESET';



export const TOUR_ADVANCED_SEARCH_REQUEST = 'TOUR_ADVANCED_SEARCH_REQUEST';
export const TOUR_ADVANCED_SEARCH_SUCCESS = 'TOUR_ADVANCED_SEARCH_SUCCESS';
export const TOUR_ADVANCED_SEARCH_FAIL = 'TOUR_ADVANCED_SEARCH_FAIL';
export const TOUR_ADVANCED_SEARCH_RESET = 'TOUR_ADVANCED_SEARCH_RESET';


export const TOUR_COMMENT_DELETE_REQUEST = 'TOUR_COMMENT_DELETE_REQUEST';
export const TOUR_COMMENT_DELETE_SUCCESS = 'TOUR_COMMENT_DELETE_SUCCESS';
export const TOUR_COMMENT_DELETE_FAIL = 'TOUR_COMMENT_DELETE_FAIL';
export const TOUR_COMMENT_DELETE_RESET = 'TOUR_COMMENT_DELETE_RESET';

export const TOUR_COMMENT_UPDATE_STATUS_REQUEST = 'TOUR_COMMENT_UPDATE_STATUS_REQUEST';
export const TOUR_COMMENT_UPDATE_STATUS_SUCCESS = 'TOUR_COMMENT_UPDATE_STATUS_SUCCESS';
export const TOUR_COMMENT_UPDATE_STATUS_FAIL = 'TOUR_COMMENT_UPDATE_STATUS_FAIL';
export const TOUR_COMMENT_UPDATE_STATUS_RESET = 'TOUR_COMMENT_UPDATE_STATUS_RESET';